### ISSUE TITLE
How to connect with raspberry pi?

### ISSUE THREAD

**Issue by Brian040101** [aelmiger/lane_detection#3]
when i process the lane_detection_script.py, it stuck in "WAITING FOR Raspberry pi"

**Comment by aelmiger** [comment]
This repo was created as part of a University course. The hardware was made up of a jetson nano and a connected Raspberry Pi.
Unfortunately, I do not have access to the hardware anymore and cannot give you proper support. I do believe that the Raspberry Pi was connected via Ethernet cable. You will probably have to rewrite the code to fit your hardware. The RPi was not part of the algorithm, but used to control the vehicle.
